### ISSUE TITLE
rabbitTemplate创建为空，启动报错

### ISSUE THREAD

**Issue by leiyanwen** [fqlee/canal-client#1]
private static AmqpTemplate rabbitTemplate = (AmqpTemplate) SpringContextUtil.getBean("rabbitTemplate");

**Comment by fqlee** [comment]
本地rabbitmq配置有没有声明


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: leiyanwen <notifications@github.com&gt;
发送时间: 2019年12月13日 10:33
收件人: fqlee/canal-client <canal-client@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[fqlee/canal-client] rabbitTemplate创建为空，启动报错 (#1)




private static AmqpTemplate rabbitTemplate = (AmqpTemplate) SpringContextUtil.getBean("rabbitTemplate");

**Comment by leiyanwen** [comment]
> 本地rabbitmq配置有没有声明发自我的iPhone
> […](#)
> ------------------原始邮件------------------发件人：leiyanwen <notifications@github.com> 发送时间：2019年12月13日10:33收件人：fqlee / canal-client <canal-client@noreply.github.com> 抄送：已订阅<subscribed@noreply.github.com> 主题：回复：[fqlee / canal-client] rabbitTemplate创建为空，启动报错（[＃1](https://github.com/fqlee/canal-client/issues/1)）私有静态AmqpTemplate rabbitTemplate =（AmqpTemplate）SpringContextUtil.getBean（“ rabbitTemplate”）; —您收到此消息是因为您已订阅此线程。直接回复此电子邮件，在GitHub上查看或取消订阅。

检查rabbitMQ声明没有问题，我将AmqpTemplate rabbitTemplate = (AmqpTemplate) SpringContextUtil.getBean("rabbitTemplate");注释掉，可以启动，生产不了消息

**Comment by fqlee** [comment]
报错信息贴一下

**Comment by leiyanwen** [comment]
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'canalRunner' defined in file [C:\Users\yurong\Desktop\canal-client\canal-client-master\target\classes\com\servingcloud\invoice\transfer\canalclient\CanalRunner.class]: Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1232) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1131) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:502) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:312) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:310) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:868) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549) ~[spring-context-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:752) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:388) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1234) [spring-boot-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.servingcloud.invoice.transfer.canalclient.CanalClientApplication.main(CanalClientApplication.java:20) [classes/:na]
Caused by: java.lang.ExceptionInInitializerError: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_144]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_144]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:170) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1224) ~[spring-beans-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	... 16 common frames omitted
Caused by: java.lang.NullPointerException: null
	at com.servingcloud.invoice.transfer.canalclient.SpringContextUtil.getBean(SpringContextUtil.java:21) ~[classes/:na]
	at com.servingcloud.invoice.transfer.canalclient.CanalRunner.<clinit>(CanalRunner.java:33) ~[classes/:na]
	... 23 common frames omitted
